services:
  - type: web
    name: companie-management
    runtime: node
    region: oregon
    plan: free
    # Install server & client deps, then build the client
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    # Ensure server production deps are installed at start, then run the server
    startCommand: npm ci --prefix server --production && npm run start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
